version: '3.7'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: mysql
    restart: always
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: madrid
      MYSQL_USER: 42usuario
      MYSQL_PASSWORD: test1234
    volumes:
      - ./shemas:/var/lib/mysql:rw
    networks:
      mysql_network:
        aliases:
          - mysql_host
volumes:
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge




